### ISSUE TITLE
terminal state is not saved in session

### ISSUE THREAD

**Issue by dudicoco** [coffebar/neovim-project#11]
When moving between projects the terminal state is not saved within the session.
I have tried this with `toggleterm`, `floaterm` and the native `:terminal`.

**Comment by coffebar** [comment]
Hi, terminal buffers (including toggleterm) are [excluded from the neovim-session-manager](https://github.com/Shatur/neovim-session-manager/issues/61#issuecomment-1307052740) to not be a part of saved session.
I believe that nvim's :mks command doesn't have a logic how to save the terminal state. It just doesn't work.
And it is even more complex, if the terminals are controlled by third-party plugins.

If you have suggestion how to implement this, please, I will be happy to see this feature.

You may also open an issue in the [neovim-session-manager](https://github.com/Shatur/neovim-session-manager), because this plugin actually handles sessions saving.

**Comment by dudicoco** [comment]
Thanks @coffebar.

I am familiar with the linked issue, but it doesn't specify that terminal buffers are excluded by default.

After opening this issue I have tested https://github.com/folke/persistence.nvim and `:mks` and indeed terminal state is not preserved.

I guess the best route would be to manage projects/sessions with tmux instead since it persists everything within the session.

Thanks for this great project anyway!
