### ISSUE TITLE
[Feat Request] Load different types of projects in telescope

### ISSUE THREAD

**Issue by j-barnak** [coffebar/neovim-project#21]
Would it be possible to have a feature where you could load different projects (e.g., C, C++, Python, Notes) in telescope

Something along the lines of

```
Telescope neovim-project group_1
Telescope neovim-project group_2
```

?

**Comment by coffebar** [comment]
I don't always have a project in one language, it can be partially in different languages. Therefore, it is logically impossible for me to divide the projects in this way.
However, if you mean that the groups are created by the user, and have a logical meaning only that the user sets, then I think this information can be entered through the configuration of the plugin, as well as paths for projects. However, I do not see an option how to do it beautifully, to preserve compatibility and so that the configuration does not look ugly. You can think about it.

As an alternative, you can make groups in your folder structure:

> ~/projects/cpp/project1
> ~/projects/cpp/project2
> ~/projects/python/project1
> ~/projects/c/project1

so when you search in Telescope, you will see cpp\c\python folder in path like that:

![image](https://github.com/coffebar/neovim-project/assets/3100053/b5d51027-6c9f-482b-a4a0-0a2efd0873c9)

**Comment by j-barnak** [comment]
Understandable. I appreciate the response. It's obviously not a deal-breaker. Thanks!
