### ISSUE TITLE
alpha and neovim-project

### ISSUE THREAD

**Issue by sethen** [coffebar/neovim-project#34]
Love the plugin.

Currently I have the plugin configured like so:

```lua
return {
   'coffebar/neovim-project',
   opts = {
      dashboard_mode = true,
      projects = {
         '~/Developer/*',
      },
   },
   init = function()
      vim.opt.sessionoptions:append('globals')
   end,
   dependencies = {
      { 'nvim-lua/plenary.nvim' },
      { 'nvim-telescope/telescope.nvim' },
      { 'Shatur/neovim-session-manager' },
   },
   lazy = false,
   priority = 100,
}
```

You will notice I have `dashboard_mode = true`.  I do enjoy having alpha on when I start up my editor.  When I have it marked as `false` neovim-project does the right thing and boots up the file with the right directory.  However, I see a flash of the dashboard for a split second and it's rather annoying.

When it's marked as `true` I get alpha but the directory does not change correctly to the last directory I was in.

So, a couple of questions:
1.  Is it possible to avoid the flash of the dashboard somehow when `dashboard_mode` is `false`?
2.  Is it possible to have have `dashboard_mode = true` and still change the working tree in to the last directory I was in?

**Comment by coffebar** [comment]
1. alpha opens first, then session restoring. So, if the first thing is not needed, obviously will be nice if you disable it (disable or postpone plugin loading by using your plugin manager). Maybe you need to do some Lua coding in your config files if you prefer some special cases with heavy logic.

2. There is no such function. I don't see the practical point of adding this to the repository. You can make the following function within your configuration: read one line from the file where the list of projects is stored and pass it to the vim's built-in function to change the CWD.

To be honest, I don't understand why people want to use a dashboard with this plugin, because I immediately start working with the file when I open the editor. Or use something like telescope to navigate

**Comment by sethen** [comment]
> To be honest, I don't understand why people want to use a dashboard with this plugin, because I immediately start working with the file when I open the editor. Or use something like telescope to navigate

Some folks don't always want to go back to the file they were last working in.  Some folks have recent files on their dashboard that allows for quick selection.  I understand what you're saying though.

Thanks for your comment!
