### ISSUE TITLE
Allow autoload_mode = config.AutoloadMode.GitSession

### ISSUE THREAD

**Issue by thecontinium** [coffebar/neovim-project#39]
Hi 

I would like to be able to set [autoload](https://github.com/Shatur/neovim-session-manager?tab=readme-ov-file#autoload-mode) mode in session_manager. 

In particular I would like to set GitSession so that when I am in a sub directory of a git project root it will automatically open this rather than the last session option.

Maybe there is a way to configure this but I haven't been able to get it to work ?

Thanks

**Comment by coffebar** [comment]
Nope, `AutoloadMode` will be [overwritten](https://github.com/coffebar/neovim-project/blob/901b778533d4025bc235adee5e1421e265a40ee4/lua/neovim-project/config.lua#L63), neovim-project doesn't give session-manager to handle startup. Neovim-project you have a permanent folder structure for your projects, which is not depends on version control systems and should not conflict with some another approach. I mean, Auto-opening sessions that not belongs to project can break something. 
If it's all about opening the project not from the root, but from a subdirectory, I think it can be done without additional options, by default. If you're ready to PR, to do this, you need to change some logic related to `utils.path.dir_matches_project` function. Instead of checking just current dir, we need to find the nearest parent dir, that is a project, and then use `vim.api.nvim_set_current_dir(project_path)`

**Comment by thecontinium** [comment]
Take a look and see if the PR makes sense. I'm using/testing this version now on a Mac.
